### PR TITLE
Bundle of changes, MQTT autodiscovery, battery voltage reading

### PR DESCRIPTION
**Pull request by Maaciej**
Changes made to run program and then some customisations.
List of things done:

	- correction of WiFi connection

	- added service of wake button

	- changed time/date formatting

	- changed data reporting

	- added mqtt autodiscovering sensors, with types and values customisation

	- changed mqtt paths

	- fixed sleep5no

	- added measuring of rssi

	- changed battery voltage moment of measure

	- changed voltage calculations with calibration

	- added code to clear file system (to clean files from original firmware), DISABLED

	- test of private config file with gitignore, with example to use in github repository, testing idea

Now I'm learning how to use git.
Next things I will present in more granular way, I hope.

### CODE REVIEW

**Comment by BeardedTinker** [comment]
Looks great - a bit overwhelming for me :)
Hope @pesor will look into this and merge if possible.

**Comment by pesor** [comment]
I will look into it, I have been following on the sideline, and the input is very interesting. 

I did look into the Autodiscover, but then spring and summer happened. 

I will really look into everything, when autumn sets in. 

I have learned a lot about the sensors this summer, which I will also share then. 

//Per

**Comment by elgansayer** [comment]
Looks great. Was about to look into similar and saw this. Thank you so much.

I am going to pull and use this .

**Comment by elgansayer** [comment]
I found several issues and have made some updates. I am just going to clean some code up and i'll fork and PR to [Maaciej <- <- <-

**Comment by elgansayer** [comment]
I found several issues and have made some updates. I am just going to clean some code up and i'll fork and PR to [Maaciej <- <- <-

**Comment by elgansayer** [comment]
image

I added back a few things, removed others. Added friendly named. Looking a lot better
Not bad.  Temperature may be wrong/

**Pull request merged**
